### PR TITLE
Add proper error propagation and option for absolute values

### PR DESCRIPTION
**Pull request by mbeckersys**
This PR consists of one upgrade for the statistics ~~and one new cmd line option~~.

### Uncertainty Propagation
For calculations that are being made, the standard deviation and mux are now [properly tracked](https://en.wikipedia.org/w/index.php?title=Propagation_of_uncertainty&oldid=858197377), so that the final result shows ratios +/- error margins, e.g.: 
```
FE             Frontend_Bound:                     14.35 +-     0.35 % Slots below           
BAD            Bad_Speculation:                     0.73 +-     0.45 % Slots below           
BE             Backend_Bound:                      49.01 +-     0.66 % Slots                 
RET            Retiring:                           35.94 +-     0.33 % Slots below
```
A simplistic version of this was already present before, but the errors were incorrectly computed and thus not meaningful. This is a better way to do it. Towards this, all measurement values were wrapped into a class `UVal`, which overloads binary operators and propagates the stddev and multiplex ratio along with the actual values. This new class also provides some formatting functions for the output classes.

### ~~Option to show absolute values~~ withdrawn, see discussion
A new command line option `--absval` has been added, which displays the absolute values of all ratios, computed by mutliplying the ratio with the clock ticks. For this one, I am not sure if my interpretation is correct when it comes to stalls. Example:

```
FE             Frontend_Bound.Frontend_Latency.ITLB_Misses:              0.17 +-     0.03 % Clocks below            ||       56,673,335 +-     9,017,420.56
FE             Frontend_Bound.Frontend_Latency.Branch_Resteers:          0.26 +-     0.04 % Clocks_Estimated below  ||       85,922,773 +-    12,487,129.47
FE             Frontend_Bound.Frontend_Latency.DSB_Switches:             0.04 +-     0.00 % Clocks below            ||       14,268,506 +-       877,964.28
FE             Frontend_Bound.Frontend_Latency.LCP:                      0.00 +-     0.00 % Clocks below            ||                0 +-             0.00

```

### CODE REVIEW

**Comment by andikleen** [comment]
Thanks. Seems useful.

The way you get the absolute values has some issues:
You only use one cycles value, but it needs to be one in the same group. Otherwise there might be an large error from multiplexing. I think this could be fixed if you add a cycles event on every metric in the collect stage (if there is already one the event scheduler will dedup it, so it should not have overhead) 

But then for the conversion have to find the right cycles event. Could be done by tracking the index in the metric class. 

This still has the issue that if the formula needs multiple groups it might have a multiplexing error. This could only be fixed by redoing the ratios and provide a parallel absolute value. This might be doable in the ratios compiler, but is a larger project. I guess that could be ignored for now.

BTW in general the multiplexing will add more errors, but it's not clear how to measure and track them.

Also converting from slots to cycles is not correct because slots is cycles*PipeLineWidth. It probably doesn't matter for percentages because just the unit is different, but it will be misleading for displaying the absolute values. You could check for the model having PipelineWidth and multiplying it with that.

The other patches look ok to me.

**Comment by mbeckersys** [comment]
Thanks for the quick response. Since the absolute values are a bit tricky, I will remove them from the PR and just keep the error propagation for you to merge. As soon as time allows, I rework the absolute values based on your comments and ship them separately.

About the multiplexing error: Indeed, as you have written, it influences stddev. I have no idea how to model this at the moment (if possible at all), but it should be easy to do later by extending the `UVal` class.

**Comment by mbeckersys** [comment]
Done.

**Comment by andikleen** [comment]
Thanks!

**Comment by andikleen** [comment]
Actually there are some failures with tl-tester now.

Can you take a look?

**Comment by mbeckersys** [comment]
Yes, I am on it.

**Comment by mbeckersys** [comment]
Follow-up on the absolute values: if I understand correctly, the complexity comes from the fact that the processor may change clock speed (or do anything equivalent) between different groups. Otherwise any cycle counter should do, since it is anyway scaled from mux ratio to full time interval. But doesn't this also mean that the ratios as computed already have the same problem? 
E.g., let's assume we have 25% port utilization measured with a 50% mux, which doesn't change over time.  Even then, the real ratio could be below or above 25%, depending on how many cycles have happened in the other 50% when we did not measure. But, you are right, it's more delicate when showing absolute values, since one might expect a certain count and not obtain it, in contrast to percentages.

**Comment by andikleen** [comment]
On Tue, Oct 02, 2018 at 05:20:11AM -0700, Martin wrote:
> Follow-up on the absolute values: if I understand correctly, the complexity
> comes from the fact that the processor may change clock speed (or do anything
> equivalent) between different groups. Otherwise any cycle counter should do,
> since it is anyway scaled from mux ratio to full time interval. But doesn't
> this also mean that the ratios as computed already have the same problem?
> E.g., let's assume we have 25% port utilization measured with a 50% mux, which
> doesn't change over time. Even then, the real ratio could be below or above
> 25%, depending on how many cycles have happened in the other 50% when we did
> not measure. But, you are right, it's more delicate when showing absolute
> values, since one might expect a certain count and not obtain it, in contrast
> to percentages.

Yes it's frequency changes, but also threads having different idle
patterns because perfmon stops in idle.

Yes there are already other multiplexing issues.

toplev tries to keep formulas of the same level in the same groups
as much as possible, but some formulas are too complex and it can't

-Andi

**Pull request merged**
